apiVersion: 1

datasources:
  - name: AnyLog
    uid: anylog-datasource
    type: simpod-json-datasource
    access: proxy
    url: http://127.0.0.1:32149
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: "dbms"
    secureJsonData:
      httpHeaderValue1: "eads"
