apiVersion: 1

datasources:
  - name: Operator-Postgres-1
    uid: operator-postgres-1
    type: postgres
    access: proxy
    url: ${PG1_HOST}:${PG1_PORT}
    user: ${PG1_USER}
    isDefault: true
    editable: true
    jsonData:
      database: ${PG1_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timeInterval: 5s
    secureJsonData:
      password: ${PG1_PASSWORD}

  - name: Operator-Postgres-2
    uid: operator-postgres-2
    type: postgres
    access: proxy
    url: ${PG2_HOST}:${PG2_PORT}
    user: ${PG2_USER}
    editable: true
    jsonData:
      database: ${PG2_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timeInterval: 5s
    secureJsonData:
      password: ${PG2_PASSWORD}

  - name: Operator-Postgres-3
    uid: operator-postgres-3
    type: postgres
    access: proxy
    url: ${PG3_HOST}:${PG3_PORT}
    user: ${PG3_USER}
    editable: true
    jsonData:
      database: ${PG3_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timeInterval: 5s
    secureJsonData:
      password: ${PG3_PASSWORD}
