# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor_data.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sensor_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_data.proto\x12\x04\x65\x61\x64s\"\x1e\n\rSensorRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"k\n\rSensorReading\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0f\n\x07voltage\x18\x02 \x01(\x01\x12\x11\n\tsensor_id\x18\x03 \x01(\t\x12\x10\n\x08latitude\x18\x04 \x01(\x01\x12\x11\n\tlongitude\x18\x05 \x01(\x01\"-\n\x12SensorDataResponse\x12\x17\n\x0fserialized_data\x18\x01 \x03(\t2\x8f\x01\n\rSensorService\x12>\n\rGetSensorData\x12\x13.eads.SensorRequest\x1a\x18.eads.SensorDataResponse\x12>\n\x10StreamSensorData\x12\x13.eads.SensorRequest\x1a\x13.eads.SensorReading0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORREQUEST']._serialized_start=27
  _globals['_SENSORREQUEST']._serialized_end=57
  _globals['_SENSORREADING']._serialized_start=59
  _globals['_SENSORREADING']._serialized_end=166
  _globals['_SENSORDATARESPONSE']._serialized_start=168
  _globals['_SENSORDATARESPONSE']._serialized_end=213
  _globals['_SENSORSERVICE']._serialized_start=216
  _globals['_SENSORSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
